behaviors:
  BasicAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      use_recurrent: false
      # sequence_length: 16
      # memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      # gail: 
      #   strength: 0.1
      #   gamma: 0.99
      #   demo_path: Assets/Demonstrations/Corridor1.demo
      #   use_actions: false
      #   use_vail: false
    # self_play:
    #   window: 10
    #   play_against_latest_model_ratio: 0.5
    #   save_steps: 20000
    #   swap_steps: 2000
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 5000

environment_parameters:
  active_obstacles: 
    curriculum:
      - name: NoObstacles # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: BasicAgent
          signal_smoothing: false
          min_lesson_length: 200
          threshold: 110 #95
        value: 0.0
      - name: OneObstacle # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: BasicAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 105 #93
        value: 1.0
      - name: TwoObstacles # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: BasicAgent
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 100 #90 # 100k pasos
          require_reset: true
        value: 2.0
      - name: ThreeObstacles
        value: 3.0
  max_obstacle_speed: 0.1
    # curriculum:
    #   - name: OnlySlowObstacles
    #     completion_criteria:
    #       measure: progress
    #       behavior: BasicAgent
    #       signal_smoothing: true
    #       min_lesson_length: 200
    #       threshold: 0.01
    #     value: 0.01
    #   - name: SlowMediumObstacles
    #     completion_criteria:
    #       measure: progress
    #       behavior: BasicAgent
    #       signal_smoothing: true
    #       min_lesson_length: 200
    #       threshold: 0.1
    #     value: 0.05
    #   - name: AllObstacles
    #     value: 0.1